1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [3]:
import numpy as np
x = np.array([1, 2, 3, 4])
print(" array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

x = np.array([0, 1, 2, 3])
print(" array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))


 array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
 array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


2. Write a NumPy program to test whether any of the elements of a given array is non-zero.


In [5]:
import numpy as np
x = np.array([1, 0, 0, 0])
print(" array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(" array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))


 array:
[1 0 0 0]
Test whether any of the elements of a given array is non-zero:
True
 array:
[0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given 


In [7]:
import numpy as np
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.00])
print(" numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))


 numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.   79.   85.   90.  150. -135.  120.  -10.   60.  100.]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True  True]
Comparison - equal within a tolerance:
True


4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.


In [8]:
import numpy as np
x=np.zeros(10)
print(" 10 zeros:")
print(x)
x=np.ones(10)
print(" 10 ones:")
print(x)
x=np.ones(10)*5
print(" 10 fives:")
print(x)


 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Write a NumPy program to create an array of the integers from 30 to70.


In [9]:
import numpy as np
x=np.arange(30,71,2)
print(" even integers from 30 to 70")
print(x) 


 even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


6. Write a NumPy program to create a 3x3 identity matrix 


In [10]:
import numpy as np
x=np.identity(3)
print('3x3 matrix:')
print(x)


3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Write a NumPy program to generate a random number between 0 and 1 


In [11]:
import numpy as np
r_n = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(r_n)


Random number between 0 and 1:
[-1.03505682]


8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution 


import numpy as np
r_n= np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(r_n)


Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the
first and las

In [13]:
import numpy as np
x = np.arange(15,55)
print(" vector:")
print(x)
print("All values except the first and last of the said vector:")
print(x[1:-1])


 vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10 


In [14]:
import numpy as np
x = np.random.randint(0, 11, 5)
print("arbitrary integers from 0 to 10:")
print(x)


arbitrary integers from 0 to 10:
[10  6 10  4  6]


11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1,
and inside 0.

In [15]:
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4,
5.


In [16]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [17]:
import numpy as np
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and
load it

In [19]:
import numpy as np
import os
x = np.arange(10)
y = np.arange(11, 20)
print(" arrays:")
print(x)
print(y)
np.savez('temp_arra.npz', x=x, y=y)
print(" 'temp_arra.npz' file:")
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)


 arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


15. Write a NumPy program to create a one dimensional array of forty pseudo-randomly generated values.
Select 

In [20]:
import numpy as np  
np.random.seed(10)
print(np.random.rand(40))


[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


16. Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number.

In [21]:
import numpy as np  
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print(" array:")
print(nums)
n = 5
print("\nElements of the said array greater than",n)
print(nums[nums > n])
n = 6
print("\nElements of the said array less than",n)
print(nums[nums < n])


 array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]
